### ISSUE TITLE
Unexpected key present?

### ISSUE THREAD

**Issue by timonbimon** [smian/pre-commit-makefile#2]
When running my pre-commit hooks, I get the following error:

```
pre-commit run --all-files
[WARNING] Unexpected key(s) present on git://github.com/smian/pre-commit-makefile: sha
```

My pre-commit-config.yml looks like this

```
repos:
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.4.0
  hooks:
  - id: reorder-python-imports
    args: [--application-directories=src]
    language_version: python3.7
- repo: https://github.com/ambv/black
  rev: 19.3b0
  hooks:
  - id: black
    language_version: python3.7
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: flake8
    args: ['--ignore=E203,E266,E501,W503', '--max-line-length=88', '--max-doc-length=88', '--max-complexity=15', '--select=B,C,E,F,W,T4,B9']
    language_version: python3.7
- repo: git://github.com/smian/pre-commit-makefile
  sha: master
  hooks:
    - id: makefile-doc
```

any ideas what might be causing the warning?
